meta_product_name: "Peetaya"
meta_title: "Peetaya - Be different"
meta_description: "Peetaya is all about traveling like a local. Book a PeetaGuide and live a unique experience."
meta_image: "logo2.png" # should exist in `app/assets/images/`

