meta_product_name: "Peetaya"
meta_title: "Peetaya - Travel different"
meta_description: "Peetaya is all about discovering new places through local eyes. Book a Peetaguide to live a unique experience."
meta_image: "logo2.png" # should exist in `app/assets/images/`

